/**
 * auto-capture.mjs
 * 
 * The self-evolution loop. After AI solves something novel:
 * 1. AI writes a script from the solution
 * 2. auto-capture registers it
 * 3. Next time, the script runs — no AI needed
 * 
 * This closes the loop so the system never asks AI twice for the same thing.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REGISTRY_FILE = join(__dirname, "script-registry.json");

/**
 * Called by AI after solving a novel problem.
 * AI passes the solution and this generates a script template.
 * 
 * @param {object} solution - { intent, code, files, pattern, trigger }
 * @returns {object} - { scriptId, scriptTemplate, registered }
 */
export function capture(solution) {
  const registry = JSON.parse(readFileSync(REGISTRY_FILE, "utf8"));
  
  // Generate script ID from intent
  const scriptId = intentToId(solution.intent);
  
  // Generate trigger phrases
  const triggers = generateTriggers(solution.intent, scriptId);
  
  // Generate questions from the pattern
  const questions = generateQuestions(solution.pattern, solution.intent);
  
  // Build the script definition
  const scriptDef = {
    id: scriptId,
    trigger: triggers,
    description: solution.intent,
    category: solution.category || "auto-captured",
    questions,
    output: solution.output || "Zo Space component",
    autoGenerated: true,
    capturedAt: new Date().toISOString(),
    pattern: solution.pattern || null,
  };
  
  // Register it
  const existing = registry.scripts.find(s => s.id === scriptId);
  if (existing) {
    Object.assign(existing, scriptDef);
  } else {
    registry.scripts.push(scriptDef);
  }
  
  registry.updatedAt = new Date().toISOString();
  writeFileSync(REGISTRY_FILE, JSON.stringify(registry, null, 2));
  
  // Generate the actual script file template
  const scriptTemplate = buildScriptTemplate(scriptId, solution);
  
  return {
    scriptId,
    scriptDef,
    scriptTemplate,
    registered: true,
    nextTime: `Script "${scriptId}" is now registered. Next time you say "${triggers[0]}", the script will run directly.`,
  };
}

/**
 * Check if a script already exists for this intent.
 */
export function isCaptured(intent) {
  const registry = JSON.parse(readFileSync(REGISTRY_FILE, "utf8"));
  const scriptId = intentToId(intent);
  return registry.scripts.some(s => s.id === scriptId);
}

/**
 * Suggest script capture to AI.
 * Returns a prompt addition telling AI to write a script.
 */
export function suggestCapture(intent, category = "component") {
  const scriptId = intentToId(intent);
  
  return `
📝 AUTO-CAPTURE RECOMMENDED

This problem appears repeatable. To avoid asking AI again:

1. Write a script at: scripts/factory/artifacts/${scriptId}.mjs
2. Use this template:

---
import { writeFileSync } from "node:fs";
import { join } from "node:path";

export default async function execute(contract, opts = {}) {
  const { answers = {}, intent = "" } = contract;
  
  // Script logic here
  
  return {
    files: [{ path: "output/path.tsx", action: "created" }],
    message: "Done.",
    code: "\\`\\`\\`tsx\\n// your component code\\n\\`\\`\\`",
  };
}
---

3. Register it in script-registry.json:
{
  "id": "${scriptId}",
  "trigger": ["${intent.toLowerCase()}", "${intent.toLowerCase().split(" ")[0]}"],
  "description": "${intent}",
  "category": "${category}",
  "questions": [],
  "output": "Zo Space component"
}

4. After writing the script, call:
node scripts/factory/intake-engine.mjs "register script ${scriptId}"
`;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function intentToId(intent) {
  return intent
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, "")
    .replace(/\s+/g, "-")
    .slice(0, 40);
}

function generateTriggers(intent, scriptId) {
  const words = intent.toLowerCase().split(/\s+/).filter(w => w.length > 2);
  const triggers = [intent.toLowerCase()];
  
  if (words.length > 1) {
    triggers.push(words.slice(0, 3).join(" "));
  }
  
  if (!triggers.includes(scriptId.replace(/-/g, " "))) {
    triggers.push(scriptId.replace(/-/g, " "));
  }
  
  return [...new Set(triggers)].slice(0, 5);
}

function generateQuestions(pattern, intent) {
  // Extract likely questions from the pattern
  const questions = [];
  
  if (pattern?.fields) {
    questions.push({
      id: "fields",
      label: "Which fields?",
      type: "select",
      options: pattern.fields,
      required: true,
    });
  }
  
  if (pattern?.type) {
    questions.push({
      id: "type",
      label: "Type?",
      type: "select",
      options: pattern.type,
      required: true,
    });
  }
  
  // Always ask these by default
  questions.push({
    id: "target-file",
    label: "Target file path (or leave empty for clipboard)",
    type: "text",
    required: false,
  });
  
  return questions;
}

function buildScriptTemplate(scriptId, solution) {
  return `/**
 * ${scriptId}.mjs
 * Auto-captured from solution: "${solution.intent}"
 * Generated: ${new Date().toISOString()}
 * 
 * ${solution.description || "Script template"}
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

export default async function execute(contract, opts = {}) {
  const { answers = {}, intent = "" } = contract;
  
  // ── Configuration ────────────────────────────────────────────
  // Customize these based on what the script needs
  // ─────────────────────────────────────────────────────────────
  
  const result = {
    files: [],
    code: ${JSON.stringify(solution.code || "", null, 2)},
    message: "Generated via auto-capture.",
  };
  
  // Write output if target is specified
  const targetFile = answers["target-file"];
  if (targetFile && result.code) {
    writeFileSync(targetFile, result.code);
    result.files.push({ path: targetFile, action: "created" });
  }
  
  return result;
}
`;
}
