#!/usr/bin/env node
/**
 * factory.mjs — Main CLI for the Script Factory
 * 
 * Usage:
 *   node factory.mjs "add a form"              — run intake
 *   node factory.mjs "scan"                   — direct command
 *   node factory.mjs "list"                   — list scripts
 *   node factory.mjs "run <script-id>"        — run specific script
 *   node factory.mjs "capture <script-id>"    — check auto-capture
 *   node factory.mjs "register <file.json>"   — register new script
 */

import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { intake, listScripts, executeScript, matchScript, loadRegistry } from "./intake-engine.mjs";
import { capture, suggestCapture, isCaptured } from "./auto-capture.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));

async function main() {
  const args = process.argv.slice(2);
  const cmd = args[0] || "";
  const rest = args.slice(1).join(" ");

  // ── Direct Commands ──────────────────────────────────────────
  switch (cmd) {
    case "list": {
      console.log("\n📜 Registered Scripts\n" + "─".repeat(60));
      const scripts = listScripts();
      if (scripts.length === 0) {
        console.log("  No scripts registered yet.");
      } else {
        for (const s of scripts) {
          const triggers = s.trigger.padEnd(35);
          const q = s.hasQuestions ? "⚙️ " : "⚡";
          console.log(`  ${q} ${s.id.padEnd(22)} ${triggers}`);
        }
      }
      console.log(`\n  Total: ${scripts.length} scripts\n`);
      return;
    }

    case "scan": {
      console.log("\n🔍 Scanning workspace...\n");
      const { default: scan } = await import("./artifacts/scan-workspace.mjs");
      const result = await scan({}, { verbose: true });
      console.log("\n" + result.message + "\n");
      return;
    }

    case "stats": {
      console.log("\n📊 Token Stats\n" + "─".repeat(60));
      const { default: tracker } = await import("../token/token-tracker.mjs");
      tracker({ action: "stats" });
      return;
    }

    case "run": {
      if (!rest) {
        console.log("Usage: factory.mjs run <script-id> [--auto-answer]");
        return;
      }
      const scriptId = rest.split(" ")[0];
      const autoAnswer = args.includes("--auto-answer");
      const registry = loadRegistry();
      const script = registry.scripts.find(s => s.id === scriptId);
      
      if (!script) {
        console.log(`Script not found: ${scriptId}`);
        console.log("Run 'factory.mjs list' to see available scripts.");
        return;
      }
      
      let answers = {};
      if (autoAnswer && script.questions.length > 0) {
        for (const q of script.questions) {
          if (q.required && q.options && q.options.length > 0) {
            answers[q.id] = q.options[0];
          }
        }
      }
      
      const contract = { scriptId, answers, intent: `run ${scriptId}` };
      const result = await executeScript(scriptId, contract, true);
      
      if (result.ok) {
        console.log("\n✅ Done:", result.result?.message);
      } else {
        console.log("\n❌ Error:", result.error);
      }
      return;
    }

    case "capture": {
      if (!rest) {
        console.log("\n🤖 Auto-Capture Status\n" + "─".repeat(60));
        const captured = loadRegistry().scripts.filter(s => s.autoGenerated);
        if (captured.length === 0) {
          console.log("  No auto-captured scripts yet.");
        } else {
          console.log(`  ${captured.length} scripts captured:\n`);
          for (const s of captured) {
            console.log(`  • ${s.id} — captured ${s.capturedAt}`);
          }
        }
        return;
      }
      
      // Check if an intent is already captured
      if (isCaptured(rest)) {
        console.log(`✅ "${rest}" is already captured. Script will run directly.`);
      } else {
        console.log(suggestCapture(rest));
      }
      return;
    }

    case "register": {
      if (!rest || !existsSync(rest)) {
        console.log("Usage: factory.mjs register <script-def.json>");
        return;
      }
      const def = JSON.parse(readFileSync(rest, "utf8"));
      const { registerScript } = await import("./intake-engine.mjs");
      const result = registerScript(def);
      console.log(`\n✅ Script registered: ${result.id} (${result.action})\n`);
      return;
    }

    case "gateway": {
      // Print AI gateway payload for a given prompt
      const payload = intake(rest || "do something", { verbose: false });
      console.log(JSON.stringify(payload, null, 2));
      return;
    }

    case "help": {
      printHelp();
      return;
    }

    case "":
    case "help":
    case "--help":
    case "-h": {
      printHelp();
      return;
    }

    default: {
      // Treat as a prompt
      console.log(`\n🎯 Intake: "${cmd} ${rest}"\n`);
      const result = await intake(`${cmd} ${rest}`, { verbose: true });
      
      if (result.stage === "DONE") {
        console.log("\n✅ Complete:", result.result?.message);
      } else if (result.stage === "AI_GATEWAY") {
        console.log("\n🤖 AI Gateway triggered.");
        if (result.aiPayload?.autoCapture) {
          console.log(suggestCapture(`${cmd} ${rest}`));
        }
      } else if (result.stage === "QUESTIONS") {
        console.log("\n📋 Script matched. Answer questions above, then re-run.");
      }
      return;
    }
  }
}

function printHelp() {
  console.log(`
📜 Script Factory CLI

Usage: factory <command> [args]

Intake (finds script and executes):
  factory "add a form"              Run intake for "add a form"
  factory "add button" --auto      Auto-answer questions, execute

Direct commands:
  factory list                      List all registered scripts
  factory scan                      Scan workspace, emit tree
  factory stats                     Show token usage
  factory run <id> [--auto]        Run a specific script directly
  factory capture [intent]         Check/confirm auto-capture status
  factory register <file.json>      Register a new script
  factory help                      Show this help

Examples:
  factory "add a form"             → intake engine → script → execute
  factory "scan"                   → workspace scan script
  factory "tokens"                 → token stats script
  factory list                     → show all available scripts
  factory run page-add --auto      → run page-add with defaults
`);
}

main().catch(err => {
  console.error(`Factory error: ${err.message}`);
  process.exit(1);
});
